insert into autod (mark, model, engine, fuel, price, image) values ('B-Series Plus', 'Xterra', 'V6', 'elekter', 501, '/eu.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Laser', 'Escape', 'V6', 'elekter', 542, '/mauris.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Stylus', 'W201', 'V6', 'gaas', 801, '/semper/interdum/mauris/ullamcorper.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Quest', 'Probe', 'V8', 'diisel', 893, '/diam/nam/tristique/tortor.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Ram Van 2500', 'S2000', 'V8', 'diisel', 386, '/eget/eros.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Yukon', 'Fiero', 'V6', 'bensiin', 623, '/nisi/nam/ultrices/libero/non/mattis.png');
insert into autod (mark, model, engine, fuel, price, image) values ('LS', 'Express 1500', 'V8', 'diisel', 437, '/mus/vivamus/vestibulum/sagittis/sapien.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Hombre', 'Camaro', 'V12', 'elekter', 684, '/eros/viverra/eget/congue.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Grand Caravan', 'Altima', 'V8', 'gaas', 146, '/erat/id/mauris.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Civic GX', 'Murano', 'V8', 'diisel', 799, '/cursus/id/turpis/integer.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Corolla', 'Concorde', 'V12', 'bensiin', 318, '/posuere/cubilia/curae/nulla/dapibus/dolor/vel.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('New Yorker', 'Sierra 1500', 'V8', 'elekter', 411, '/in/lectus/pellentesque.json');
insert into autod (mark, model, engine, fuel, price, image) values ('GTI', 'Sterling', 'V8', 'gaas', 867, '/cursus/id/turpis/integer/aliquet.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('S40', 'Rendezvous', 'V8', 'elekter', 276, '/turpis/sed.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Range Rover Sport', 'Mustang', 'V8', 'elekter', 664, '/fusce/lacus/purus/aliquet/at/feugiat/non.json');
insert into autod (mark, model, engine, fuel, price, image) values ('57', 'GranTurismo', 'V12', 'elekter', 721, '/massa/id.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Phaeton', 'Bronco', 'V6', 'bensiin', 579, '/nec/dui.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Odyssey', 'STS-V', 'V12', 'diisel', 468, '/nulla/sed/accumsan/felis/ut/at/dolor.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Quest', 'Envoy XUV', 'V8', 'gaas', 782, '/congue/etiam.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Grand Cherokee', 'Classic', 'V12', 'diisel', 766, '/est/et/tempus/semper.html');
insert into autod (mark, model, engine, fuel, price, image) values ('Pajero', 'Ram', 'V6', 'elekter', 576, '/sapien.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Tacoma', 'Milan', 'V12', 'bensiin', 651, '/mollis.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('GTI', 'RL', 'V12', 'gaas', 965, '/ante/ipsum/primis.html');
insert into autod (mark, model, engine, fuel, price, image) values ('Savana 3500', 'Elantra', 'V12', 'gaas', 432, '/volutpat/erat/quisque/erat/eros/viverra/eget.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Intrepid', 'Navajo', 'V12', 'gaas', 150, '/nisl/ut/volutpat.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Vandura 3500', 'S-Class', 'V8', 'gaas', 129, '/tortor/risus/dapibus/augue/vel/accumsan.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Silhouette', 'Regal', 'V6', 'diisel', 603, '/lobortis/est/phasellus/sit/amet/erat.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('C-Class', '400E', 'V6', 'elekter', 640, '/ligula/sit.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Cavalier', 'Viper', 'V6', 'diisel', 649, '/nam/congue/risus/semper/porta/volutpat.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Accord', 'Rio', 'V8', 'bensiin', 664, '/viverra.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Econoline E150', 'LTD Crown Victoria', 'V8', 'elekter', 527, '/eget/orci/vehicula/condimentum/curabitur/in.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Montana', 'RL', 'V8', 'elekter', 486, '/aliquam/sit/amet/diam.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Eldorado', 'Vibe', 'V8', 'diisel', 355, '/tempus/vivamus/in/felis/eu.html');
insert into autod (mark, model, engine, fuel, price, image) values ('RVR', 'Clubman', 'V6', 'bensiin', 966, '/venenatis/lacinia/aenean.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Canyon', 'Avenger', 'V12', 'diisel', 604, '/lobortis/sapien.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Excursion', 'Tacoma Xtra', 'V12', 'gaas', 391, '/ultrices.html');
insert into autod (mark, model, engine, fuel, price, image) values ('Ram 3500 Club', 'Outlander', 'V6', 'diisel', 814, '/lobortis/est/phasellus/sit/amet/erat/nulla.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('S4', 'M5', 'V8', 'diisel', 373, '/morbi/ut/odio.js');
insert into autod (mark, model, engine, fuel, price, image) values ('911', 'Savana', 'V6', 'gaas', 505, '/nullam/porttitor.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Eclipse', 'SL-Class', 'V12', 'diisel', 828, '/sit/amet/cursus/id/turpis.xml');
